Repository OpenVicProject/OpenVic-Dataloader, pull requests merged in 2024-01, with the labels that each got.

#34 Fix includes
  include/openvic-dataloader/csv/LineObject.hpp
  include/openvic-dataloader/csv/Parser.hpp
  include/openvic-dataloader/detail/BasicParser.hpp
  include/openvic-dataloader/detail/Concepts.hpp
  include/openvic-dataloader/v2script/Parser.hpp
  src/headless/main.cpp
  src/openvic-dataloader/csv/Parser.cpp
  src/openvic-dataloader/detail/LexyReportError.hpp
  src/openvic-dataloader/detail/Warnings.hpp
  src/openvic-dataloader/v2script/AbstractSyntaxTree.cpp
  src/openvic-dataloader/v2script/AiBehaviorGrammar.hpp
  src/openvic-dataloader/v2script/DecisionGrammar.hpp
  src/openvic-dataloader/v2script/EventGrammar.hpp
  src/openvic-dataloader/v2script/Parser.cpp
  src/openvic-dataloader/v2script/SimpleGrammar.hpp
Labels: bug

#35 Expanded v2script character list to support Windows-1251
  src/openvic-dataloader/v2script/SimpleGrammar.hpp
Labels: enhancement

#36 Fixed BasicParser::_file_path relying on externally controlled memory
  include/openvic-dataloader/csv/LineObject.hpp
  include/openvic-dataloader/detail/BasicParser.hpp
  src/openvic-dataloader/detail/BasicParser.cpp
  src/openvic-dataloader/detail/Errors.hpp
  src/openvic-dataloader/detail/LexyReportError.hpp
  src/openvic-dataloader/detail/Warnings.hpp
  src/openvic-dataloader/v2script/Parser.cpp
Labels: bug, enhancement

#39 Update build workflow actions
  .github/workflows/builds.yml
Labels: enhancement
